### ISSUE TITLE
Support for Raspberry PI

### ISSUE THREAD

**Issue by malavv** [peteward44/docker-godaddy-ddns#3]
Thanks for your repo, it does its job perfectly.

Yet, as many, I have a Raspberry PI home server, and the `gliderlabs/alpine:3.8` base image just won't work. 

I forked the repo, just to swap the import to `resin/raspberry-pi-alpine:3.8`, but I am sure there should be an easier way to do this. I am not used to working in the Docker ecosystem, but I wanted to suggest this fix for upstream integration. 

Cheers!

**Comment by peteward44** [comment]
Hi, this is because i've only built the x86_64 version whilst the RPI runs arm32v6. I've never made a cross-arch docker image so bear with me whilst i figure it out

**Comment by peteward44** [comment]
OK, i've pushed new tags to docker hub. According to the guide I followed, you should be able to use `peteward44/godaddy-ddns:latest` and it'll automagically use the arm32 image for you. I have no ARM hardware so i can't test it, i'll be interested to know if it worked. Thanks

**Comment by malavv** [comment]
It works flawlessly, thanks!
I'll delete my fork and use yours directly.
