### ISSUE TITLE
Latest release doesn't start

### ISSUE THREAD

**Issue by JayNewstrom** [peteward44/docker-godaddy-ddns#7]
Hi, I've been trying out the new release, but I can't get it running. I've tried on x86 and on arm. The image pulls, but won't output anything to the logs.

```
Digest: sha256:a9888241c90b5252f6db7772db46ab5b5fd7f766d1e1e86f41f552459f911d5f
Status: Downloaded newer image for peteward44/godaddy-ddns:latest
```

**Comment by peteward44** [comment]
i'm running the latest on x86 and it appears to be working. Give it at least an hour to see if it's updating

**Comment by JayNewstrom** [comment]
Ok. I was able to get it running on x86. It just took MUCH longer than I expected to start.
