### ISSUE TITLE
GoDaddy changed their api contract, receiving status 403

### ISSUE THREAD

**Issue by Maroko** [peteward44/docker-godaddy-ddns#8]
To hopefully save someone's time, GoDaddy changed their api contract. You need 10-50 domains or an subscription to use the DNS update:

https://www.reddit.com/r/godaddy/comments/1bl0f5r/am_i_the_only_one_who_cant_use_the_api/

https://www.reddit.com/r/godaddy/comments/1chs1j8/godaddy_access_denied_via_apicall/

**Comment by peteward44** [comment]
Thanks for letting me know, i'll update the README with this information
